feat : 카테고리 메뉴 선택 API 작성
2022-mwomeokji/2022-MMG pull request #56
Opened 2022-08-10 11:53 UTC by nova-deepdark

## 작업내용
- 카테고리 선택 API 작성완료
- 카테고리 선택 후 랜덤 선택 API 작성 미완료
- resolved: #카테

<br>

## 주요 변경점
- 주요 변경사항에 대해 적어주세요.
<br>

## 유의할 점 (optional)
- 팀원이 유의해야할 변경 사항이나 로직이 생겼다면 적어주세요.
<br>

## To Reviewers (optional)
- 리뷰어에게 부탁할 내용(ex.~부분 도움 부탁합니다, ~부분 한 번 더 검토 부탁드려요) 이 있다면 적어주세요.

2022-08-10 13:22 UTC, domo7304 requested changes
![image](https://user-images.githubusercontent.com/69956503/183911495-0d613691-4923-48dd-be57-1e445389ca70.png)

우리랑 비슷한 사례가 있을까 찾아봤는데, 위 이미지에서 보면 drink 라는 domain 아래로 drink, category 가 있잖아? 
우리 케이스의 경우에도 category 와 dish 는 데이터베이스 상 다른 테이블은 맞지만, <a href=https://private-space.tistory.com/94>도메인 군집</a> 으로 생각해보면 category 와 dish 를 한 군집으로 보고 묶는 게 더 깔끔하겠다는 생각이 들어서 하나로 묶을까 하거든, 어떻게 생각하는지 의견 남겨줘!

-> category가 하나밖에 없으니까 그 방향이 더 맞는 방향인거같다 그 방향로 수정할께! , dish(category/dish)이렇게 진행할께!

2022-08-10 13:22 UTC, domo7304 commented on backend/src/main/java/com/umc/mwomeokji/domain/category/application/CategoryServiceImpl.java
> +        return categoryMapper.toCategoryNameResponse(categoryRepository.findById(id).orElseThrow(NotFoundDishException::new));
id 를 통해서 카테고리만 단독으로 가져와야하는 기능이 아직 없다고 생각했는데, 혹시 어떤 기능인지 알 수 있을까?

2022-08-10 13:22 UTC, domo7304 commented on backend/src/main/java/com/umc/mwomeokji/domain/category/domain/Category.java
> +    private List<Category> categoryDishesList = new ArrayList<>();  //이부분은 카테고리음식 리스트로 적는게 이해하기 편할 것 같아
이 부분을 양방향 관계로 처리할까 생각을 해봤는데, DishRepository 쪽에서 findAllByCategory(Category) 쿼리메소드로 가져오는 게 조금 더 나을 거 같다고 생각했어, 혹시 어떻게 생각해?

2022-08-10 16:55 UTC, nova-deepdark commented on backend/src/main/java/com/umc/mwomeokji/domain/category/application/CategoryServiceImpl.java
> +        return categoryMapper.toCategoryNameResponse(categoryRepository.findById(id).orElseThrow(NotFoundDishException::new));
아 내가 도메인 안에 category랑 dish랑 따로 분리됬다고 착각해서 그렇게 진행한거같아 dish 꺼 가져오기만 하면 되는거 맞지?

2022-08-10 16:56 UTC, nova-deepdark commented on backend/src/main/java/com/umc/mwomeokji/domain/category/domain/Category.java
> +    private List<Category> categoryDishesList = new ArrayList<>();  //이부분은 카테고리음식 리스트로 적는게 이해하기 편할 것 같아
이거는 오늘 회의 진행할 때 다시 설명해줄래?

2022-08-11 01:42 UTC, domo7304 commented on backend/src/main/java/com/umc/mwomeokji/domain/category/domain/Category.java
> +    private List<Category> categoryDishesList = new ArrayList<>();  //이부분은 카테고리음식 리스트로 적는게 이해하기 편할 것 같아
오케오케!

2022-08-11 01:45 UTC, domo7304 commented on backend/src/main/java/com/umc/mwomeokji/domain/category/application/CategoryServiceImpl.java
> +        return categoryMapper.toCategoryNameResponse(categoryRepository.findById(id).orElseThrow(NotFoundDishException::new));
응응 맞아, 카테고리 선택하는 페이지에서 카테고리를 모두 렌더링 해야하니 전부 리스트로 가져오는 방식으로 변경하자

2022-08-15 16:12 UTC, closed without merging